baseURL = "https://mbaelde.github.io/"
languageCode = "en-us"
title = "Maxime Baelde, Ph.D"
theme = ""

[params]
  description = "Senior Data Scientist | Machine Learning Engineer<br>Ph.D. in Artificial Intelligence<br>Music Producer @ [MB Prod](https://mbprod-studio.com/)"
  avatar = "/images/maxime.jpg"
  math = true

  [params.social]
    github = "https://github.com/mbaelde"
    email = "baelde.maxime@gmail.com"
    scholar = "https://scholar.google.fr/citations?hl=fr&view_op=list_works&user=zhw-B7IAAAAJ"
    linkedin = "https://www.linkedin.com/in/maxime-baelde-phd/"
    bandcamp = "https://fractonband.bandcamp.com/"

  [params.features]
    research = true
    publications = true
    code = true
    music = true

[menu]
  [[menu.main]]
    name = "About Me"
    url = "#about"
    weight = 10
  [[menu.main]]
    name = "Research & Teaching"
    url = "#research"
    weight = 20
  [[menu.main]]
    name = "Publications"
    url = "#publications"
    weight = 30
  [[menu.main]]
    name = "Code"
    url = "#code"
    weight = 40
  [[menu.main]]
    name = "Music"
    url = "#music"
    weight = 50

[markup.goldmark.renderer]
  unsafe = true
